apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      name: mysql
  selector:
    {{- include "database-service.selectorLabels" . | nindent 4 }}
